app.ActionTypes = {
  SET_RETROSPECTIVE: 'SET_RETROSPECTIVE',
  OPEN_DIALOG_LABEL: 'OPEN_DIALOG_LABEL',
  CREATE_LABEL: 'CREATE_LABEL',
  UPDATE_LABEL: 'UPDATE_LABEL',
  DESTROY_LABEL: 'DESTROY_LABEL',
  DRAG_START_LABEL: 'DRAG_START_LABEL',
  DRAG_END_LABEL: 'DRAG_END_LABEL',
  DROP_LABEL: 'DROP_LABEL',
  ADD_USER: 'ADD_USER'
};
