language: ruby

rvm:
  - 2.4.1

sudo: false

cache:
  bundler: true
  directories:
    - $HOME/.yarn-cache

before_install:
  - nvm install 8.9.0
  - npm config set spin false
  - npm install -g yarn

before_script:
 - cp config/database.yml.travis config/database.yml
 - yarn install
 - yarn run build

script:
  - 'RAILS_ENV=test bundle exec rake db:drop db:create db:migrate spec'
  - 'yarn run flow'
  - 'yarn run test'
