language: ruby

rvm:
  - 2.3.1

sudo: false

cache: bundler

before_script:
  - cp config/database.yml.travis config/database.yml

script: 'RAILS_ENV=test bundle exec rake db:drop db:create db:migrate spec'